import { useEffect, useState } from 'react';

const features = [
  { number: '01', eyebrow: 'TEAM IP GAME', title: '战队专属游戏', text: '把战队 DNA、阵容关系与真实 BP 记录变成可游玩的战队经理。', tone: 'yellow', mark: 'AG', detail: '阵容化学反应 87 / 100', logo: '/assets/ag-logo.png' },
  { number: '02', eyebrow: 'FAN CONTENT STUDIO', title: '粉丝内容生产', text: '从一场比赛事实，批量生成海报、选手卡、战报与社交内容包。', tone: 'pink', mark: 'CONTENT', detail: '4 种输出已就绪' },
  { number: '03', eyebrow: 'CITY MATCHDAY', title: '城市电竞地图', text: '连接主场战队、赛程与城市节点，组织一条可参与的比赛日路线。', tone: 'blue', mark: 'SH', detail: 'POI / 场馆待接入', logo: '/assets/edgm-logo.png' },
] as const;

export function ApplicationsPage() {
  const [active, setActive] = useState(0);
  const [menuOpen, setMenuOpen] = useState(false);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === 'ArrowRight') setActive((value) => (value + 1) % features.length); if (event.key === 'ArrowLeft') setActive((value) => (value + features.length - 1) % features.length); if (event.key === 'Escape') setMenuOpen(false); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, []);
  return (
    <main className="origin-home">
      <header className="origin-nav"><a className="origin-brand" href="#top" aria-label="KPL Knowledge Asset home"><span className="brand-dot" />KPL<span className="brand-muted">/ ASSET</span></a><nav className={menuOpen ? 'nav-links is-open' : 'nav-links'}><a href="#experience">体验</a><a href="#applications">应用</a><a href="#ledger">资产账本</a></nav><div className="nav-actions"><span className="nav-status"><i />DATA ONLINE</span><button className="menu-button" type="button" onClick={() => setMenuOpen((open) => !open)} aria-label="打开菜单"><span /><span /></button></div></header>
      <section className="origin-hero" id="top"><div className="hero-media" aria-label="星云背景视频预留区域"><div className="media-cross cross-a" /><div className="media-cross cross-b" /><span className="media-label">NEBULA MOTION / MEDIA SLOT</span><span className="media-note">VIDEO SOURCE PENDING</span><div className="media-rings" /></div><div className="hero-copy" id="experience"><p className="hero-kicker">KPL KNOWLEDGE ASSET / 2026</p><h1>让赛事事实<br /><em>开始发生</em></h1><p className="hero-description">23 个赛季，3,399 个节点，111,313 条关系。<br />从一张知识图谱，进入游戏、内容和城市。</p></div><div className="hero-footer"><span>SCROLL TO EXPLORE</span><span className="hero-line" /><span>01 / 03</span></div></section>
      <section className="feature-section" id="applications"><div className="section-intro"><p className="section-kicker">ONE GRAPH / THREE WORLDS</p><h2>一份资产，<br /><em>三种体验。</em></h2><p>每一项应用都由真实赛事关系驱动。选择一个方向，查看它如何从数据变成可使用的产品。</p><div className="section-count"><b>03</b><span>APPLICATIONS<br />READY TO BUILD</span></div></div><div className="feature-rail">{features.map((feature, index) => <article className={`feature-card tone-${feature.tone} ${index === active ? 'is-active' : ''}`} key={feature.number} onMouseEnter={() => setActive(index)}><div className="card-top"><span>{feature.number}</span><span>{feature.eyebrow}</span><span>↗</span></div><div className="card-art">{feature.logo ? <img src={feature.logo} alt="" /> : <div className="art-type">{feature.mark}</div>}<div className="art-grid" /><span className="art-status">{feature.detail}</span></div><div className="card-copy"><h3>{feature.title}</h3><p>{feature.text}</p><button type="button">打开应用 <span>↗</span></button></div></article>)}</div><div className="rail-controls"><button type="button" onClick={() => setActive((active + features.length - 1) % features.length)} aria-label="上一个应用">←</button><div>{features.map((feature, index) => <button className={index === active ? 'is-current' : ''} type="button" onClick={() => setActive(index)} key={feature.number} aria-label={`查看${feature.title}`}><span /></button>)}</div><button type="button" onClick={() => setActive((active + 1) % features.length)} aria-label="下一个应用">→</button></div></section>
      <section className="asset-strip" id="ledger"><div><span className="section-kicker">THE SOURCE</span><h2>所有体验，<br />都有出处。</h2></div><div className="ledger-numbers"><span><b>23</b>赛季</span><span><b>332</b>选手</span><span><b>132</b>英雄</span><span><b>2,875</b>系列赛</span></div><p>从俱乐部、选手、英雄、比赛到赛季，事实可回溯，模板可替换，应用可持续生长。</p></section><footer className="origin-footer"><span>KPL KNOWLEDGE ASSET</span><span>BUILT FROM THE GAME</span><span>2026 ↗</span></footer>
    </main>
  );
}
